version: "3"

services:
  test_plrust_postgres:
    container_name: test_plrust_postgres
    build: 
      context: .
    environment:
      POSTGRES_USER: demo_plrust
      POSTGRES_PASSWORD: demo_plrust
      POSTGRES_DB: demo_plrust
    volumes:
      - demo_plrust_postgres:/var/lib/postgresql/data

volumes:
  demo_plrust_postgres: